import java.util.Random;

public class RealGenerator implements IRandomValueGenerator{
	
	private int value;
	Random randomGenerator;
	
	public RealGenerator(){
		this.randomGenerator=new Random();
		this.value=0;
	}
	//each time this method is called a new value is generated by the Generator 
	public int getValue(int lowest, int highest){
		value=randomGenerator.nextInt((highest-lowest+1))+lowest;
		return value;
	}

}
