import java.util.Random;

public class RealGenerator implements IRandomValueGenerator{
	
	private int value;
	Random randomGenerator;
	
	public RealGenerator(){
		this.randomGenerator=new Random();
		this.value=0;
	}
	
	//each time this method is called a new value is generated by the Generator 
	public int getValue(int lowest, int highest){
		value=randomGenerator.nextInt((highest-lowest+1))+lowest;
		return value;
	}
	//The probability of the event happening is equal to the probability of selecting a number
	//between 0 and the probability(p). This method allows that the likelihood of selecting a
	//winning number (almost) exactly mirrors the probability of the event happening.
	public boolean getBoolean(double p){
		value=getValue(1,100);
		if (value>0 && value<(p*100+1)){
			return true;// a win-the event did happen
		}
	return false;// a loss-the event did not happen
	}

}
